name: facets-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.19.5
  - pandas>=1.3.0
  - scikit-learn
  - statsmodels
  - prophet
  - pytorch
  - pytorch-forecasting
  - transformers
  - huggingface_hub
  - langchain
  - peft
  - openai
  - openpyxl==3.0.9
  - matplotlib
  - plotly
  - seaborn
  - hdbscan
  - jupyterlab
  - modal
  - pip
  - pip:
    - openai-agents
    - gradio==4.19.0
    - sentence-transformers>=2.2.0